### ISSUE TITLE
channel.publish() return type is inconsistent with amqplib

### ISSUE THREAD

**Issue by fspoettel** [onify/fake-amqplib#3]
Hey! While trying out the library, I noticed that the return type of `channel.publish` diverges from the real `amqplib`. 

The mock returns `undefined` while amqplib's `publish` returns a `boolean` going by [`@types/amqplib`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/amqplib/index.d.ts#L48) which seems to be consistent [with the actual implementation](https://github.com/squaremo/amqp.node/blob/fe53e1841d9cb41aa81c3e016a5d4ce36baba4ee/lib/connection.js#L596) of the underlying `sendContent()`.

**Comment by paed01** [comment]
Since there is no stream involved, do you think that a return value of true will be sufficient? Or should the library, somehow, try to mimic the behavior of a corked stream?

**Comment by fspoettel** [comment]
Yes that would be enough from my perspective. I saw that you added some commits to address this, thank you very much for the quick response and resolve :)

**Comment by paed01** [comment]
Haven’t published yet. But thank you.
