### ISSUE TITLE
assertQueue(undefined) doesn

### ISSUE THREAD

**Issue by fred-o** [onify/fake-amqplib#4]

**Comment by fred-o** [comment]
When calling `channel.assertQueue(undefined)` a new queue name is generated and returned to the caller, but that name is not used in the call to `broker.assertQueue()`. Further attempts to use the generated queue results in ` Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'amqp.gen-ceebcaa686' in vhost '/'`
`

**Comment by fred-o** [comment]
The fix for this would be to change this line https://github.com/onify/fake-amqplib/blob/default/index.js#L151 to 
```
          const queue = broker.assertQueue(queue, {...options, _connectionId: connection._id}, ...args);
```

**Comment by paed01** [comment]
I think I have fixed that unintended behaviour, not sure why it was there in the first place. Even tested for name not existing!? Epic misconception.

And! thank you for uncovering this bug.

**Comment by fred-o** [comment]
Grymt! Och tack för ett väldigt praktiskt lib :)

**Comment by paed01** [comment]
Det var så lite. Kul att någon använder det.

Då stänger jag butiken för denna gång.
